JPERF-836 Fix browse boards selector
atlassian/jira-software-actions pull request #29
Opened 2022-10-11 16:29 UTC by mgrzaslewicz

2022-10-12 07:07 UTC, dagguh requested changes
- [ ] changelog

2022-10-12 07:07 UTC, dagguh commented on src/main/kotlin/com/atlassian/performance/tools/jirasoftwareactions/api/page/BrowseBoardsPage.kt
> +            elementToBeClickable(By.xpath("//*[@aria-controls='board-types']"))
XPath is useful for complex hierarchical locators. Here a simple CSS selector is sufficient:
```suggestion
            elementToBeClickable(By.cssSelector("[aria-controls='board-types']"))
```

2022-10-12 07:12 UTC, dagguh commented
WRT red CI, it seems that the `BrowseBoardsPageMock` needs to include the ARIA attributes now. The mock was introduced [here](https://github.com/atlassian/jira-software-actions/pull/2) and I'm not so sure that mocking that is a good idea (not sure = could be good, could be bad). Let's try updating the mock and see how it pans out.

2022-10-12 07:15 UTC, dagguh commented
We can reproduce JPERF-836 by adding the affected Jira version to the CI matrix.
PS. we can also add some assertions in `JiraSoftwareScenarioIT` to show that `BROWSE_BOARDS` is being run successfully.

2022-10-12 10:17 UTC, mgrzaslewicz commented
> PS. we can also add some assertions in JiraSoftwareScenarioIT to show that BROWSE_BOARDS is being run successfully.
It already contained this action and the altered selector is being tested

2022-10-12 10:47 UTC, mgrzaslewicz commented
> We can reproduce JPERF-836 by adding the affected Jira version to the CI matrix.

@dagguh What do you mean? We can already see plan failing
https://server-gdn-bamboo.internal.atlassian.com/browse/RELEASE-JPTDSR

2022-10-12 11:40 UTC, dagguh submitted a review, later dismissed

2022-10-12 11:42 UTC, ewefie approved these changes

2022-10-12 11:49 UTC, pczuj commented on CHANGELOG.md
> +- Fix browse boards selector [JPERF-836]
Nit: Issue key mention is inconsistent with the previous entries in the CHANGELOG. Not sure how much this matters.

2022-10-12 11:50 UTC, pczuj approved these changes

2022-10-12 13:19 UTC, dagguh approved these changes

2022-10-12 13:36 UTC, pczuj approved these changes

2022-10-12 13:37 UTC, pczuj commented on CHANGELOG.md
> +- Fix browse boards selector [JPERF-836]
The inner peace is probably the thing for me :D

I'm fine with leaving it as it is.

2022-10-19 15:22 UTC, dagguh approved these changes

2022-10-19 15:22 UTC, dagguh commented on src/test/kotlin/com/atlassian/performance/tools/jirasoftwareactions/api/scenario/JiraSoftwareScenarioIT.kt
> -        val actionMeter = ActionMeter(
Respect for fixing deprecations :heart:

2022-10-19 15:33 UTC, merged